//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template
    {
        public string Entry { get; set; }
        public string Name { private get; set; }
        public string Level { private get; set; }
    }
}
