//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Study
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_abilities
    {
        public string AbilityID { get; set; }
        public string RangeCast { get; set; }
        public string TargetCast { get; set; }
    }
}
